services:
  nginx:
    image: nginx:1.27
    container_name: load-balancing
    volumes:
      - ./nginx-load-balancing.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "5001:80"
      - "3001:443"
    networks:
      - load-balancing
    depends_on:
      - web-api

  web-api:
    image: matteusmachhado/project-webapi
    build:
      context: ../
      dockerfile: ./src/Project.WebApi/Dockerfile
    ports:
      - "5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:5001
    deploy:
      replicas: 3
    networks:
      - load-balancing

networks:
  load-balancing: